from Model.Entities.Player import Player
from Model.Entities.Enemy import Enemy
from Model.Entities.NPC import NPC
from Model.Items.Weapon import Weapon
from Model.Items.Potion import Potion
from Model.BattleSystem import BattleSystem

player = Player("Player", 10, 7)
enemy = Enemy("Enemy", 100, 3)
#print(enemy.getHp())
chad = NPC("Chad", 10, 2)
battle1 = BattleSystem(player, enemy)
#battle1.playerAttacks()
#battle1.playerAttacks()
#print(enemy.getHp())
battle1.commenceBattle()
#battle1.enemyAttacks()
""""
print("power is: " + str(player.getPower()))
player_sword = Weapon("Sharp Sword", "Weapon", 10, 2)
player_axe = Weapon("Sharp Axe", "Weapon", 12, 3)
player.modifyGold(20)
chad.inventoryAdd(player_sword)
print(player.showInventory())
chad.playerPurchase(player, player_sword)
print(player.showInventory())
print(player_sword.getId())
print(player_axe.getId())
print(player.showEquipedItems())
player.inventoryAdd(player_sword)
print(player.showInventory())
player.inventoryAdd(player_axe)
print(player.showInventory())
player.inventoryEquip(player_sword)
print(player.showInventory())
print(player.showEquipedItems())
print("power is: " + str(player.getPower()))
print(player_sword.getDescription())
player.inventoryEquip(player_axe)
print("power is: " + str(player.getPower()))
print(player.showInventory())
print(player.showEquipedItems())
player_potion = Potion("Small Healing Potion", "Item", 5, 5)
player.inventoryAdd(player_potion)
print(player.showInventory())
print(player_potion.getDescription())
print(player.getHp())
print(enemy.getHp())
#player.attack(enemy)
#print(enemy.getHp())
enemy.attack(player)
enemy.attack(player)
enemy.attack(player)
enemy.attack(player)
print(player.getHp())
"""